AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'node_modules/**'
    - 'vendor/**'
    - 'vendor/bundle/**'
    - 'tmp/**'
    - 'log/**'
    - 'public/**'

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/SuperArguments:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/CollectionQuerying:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false



Lint/UnusedMethodArgument:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringConcatenation:
  Enabled: false